name: Deploy Dist
# on: [push,workflow_dispatch]
# on: 
on: 
    push:
        branches:
            - dev
            - 'feature/**'
        paths-ignore:
            - '.github/workflows/*'
            - README.md
    workflow_dispatch:

#     - push
#     - workflow_dispatch
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            #   run: |
            #     echo "Cloing Repo"
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Install Node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            # - name: Print Node Version
            #   run: node -v
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                # ubuntu-node-2312345
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm run test

    deploy:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install Node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                # ubuntu-node-2312345
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            - name: Deploy
              run: echo "Deploy Successfull"